---
title: "Assignment2"
author: "2722008W"
date: "2022-03-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r, echo=FALSE}
stage = read_tsv("data/UKDA-5340-tab/tab/stage_eul_2002-2020.tab") %>%
  select(IndividualID, TripID, StageDistance, StageTime, StageMode_B11ID, SurveyYear) %>%
  filter(SurveyYear == 2009 | SurveyYear == 2019) %>%
  filter(StageDistance >= 0.5) %>%
  mutate(StageMode_B11ID = factor(StageMode_B11ID, 1:13, labels = c("Public transport or active travel", "Public transport or active travel", "Private vehicle", "Private vehicle", "Private vehicle", "Private vehicle", "Public transport or active travel", "Public transport or active travel", "Public transport or active travel", "Public transport or active travel", "Public transport or active travel", "Private vehicle", "Public transport or active travel"))) %>%
  drop_na()

individual2009 = read_tsv("data/UKDA-5340-tab/tab/individual_eul_2002-2020.tab") %>%
  select(HouseholdID, IndividualID, Age_B01ID, Sex_B01ID, EthGroupTS_B02ID, SurveyYear) %>%
  filter(SurveyYear == 2009) %>%
  mutate(Sex_B01ID = factor(Sex_B01ID, 1:2, labels = c("Male", "Female")),
         EthGroupTS_B02ID = factor(EthGroupTS_B02ID, 1:2, labels = c("White", "Non-white")),
         BirthDecade = factor(Age_B01ID, 10:14, labels = c("1980-89", "1980-89", "1980-89", "1970-79", "1960-69"))) %>%
  drop_na()

individual2019 = read_tsv("data/UKDA-5340-tab/tab/individual_eul_2002-2020.tab") %>%
  select(HouseholdID, IndividualID, Age_B01ID, Sex_B01ID, EthGroupTS_B02ID, SurveyYear) %>%
  filter(SurveyYear == 2019) %>%
  mutate(Sex_B01ID = factor(Sex_B01ID, 1:2, labels = c("Male", "Female")),
         EthGroupTS_B02ID = factor(EthGroupTS_B02ID, 1:2, labels = c("White", "Non-white")),
         BirthDecade = factor(Age_B01ID, 13:15, labels = c("1980-89", "1970-79", "1960-69"))) %>%
  drop_na()

trip = read_tsv("data/UKDA-5340-tab/tab/trip_eul_2002-2020.tab") %>%
  select(TripID, IndividualID, TripPurpose_B04ID, SurveyYear) %>%
  mutate(TripPurpose_B04ID = factor(TripPurpose_B04ID, 1:8, labels = c("Commuting", "Business", "Education / escort education", "Shopping", "Other escort", "Personal business", "Leisure", "Other including just walk"))) %>%
  drop_na()

household = read_tsv("data/UKDA-5340-tab/tab/household_eul_2002-2020.tab") %>%
  filter(SurveyYear == 2019 | SurveyYear == 2009) %>%
  select(HouseholdID, HHIncQDSEngTS_B01ID, SurveyYear) %>%
  mutate(HHIncQDSEngTS_B01ID = factor(HHIncQDSEngTS_B01ID, 1:5)) %>%
  drop_na()

```

```{r}

allMerged = individual2009 %>%
  rbind(individual2019) %>%
  merge(household) %>%
  merge(stage) %>%
  merge(trip) %>%
  drop_na() %>%
  mutate(SurveyYear = factor(SurveyYear, c(2009, 2019))) %>%
  select(StageDistance, StageMode_B11ID, BirthDecade, Sex_B01ID, 
         EthGroupTS_B02ID, HHIncQDSEngTS_B01ID, TripPurpose_B04ID, SurveyYear)
```


```{r}
ggplot(allMerged %>% filter(SurveyYear == 2009), aes(x = BirthDecade, fill = StageMode_B11ID)) +
  geom_bar(position = "fill")

ggplot(allMerged %>% filter(SurveyYear == 2019), aes(x = BirthDecade, fill = StageMode_B11ID)) +
  geom_bar(position = "fill")
```
```{r}
logit2009 = glm(StageMode_B11ID ~ BirthDecade + StageDistance + Sex_B01ID + EthGroupTS_B02ID + HHIncQDSEngTS_B01ID + TripPurpose_B04ID, family="binomial", data=allMerged %>% filter(SurveyYear == 2009), x=T)

logit2019 = glm(StageMode_B11ID ~ BirthDecade + StageDistance + Sex_B01ID + EthGroupTS_B02ID + HHIncQDSEngTS_B01ID + TripPurpose_B04ID, family="binomial", data=allMerged %>% filter(SurveyYear == 2019), x=T)

```